name: Generar APK de FireGuard

on:
  push:
    branches: [ main ] # O el nombre de tu rama principal
  workflow_dispatch: # Esto permite darle al botón de "Play" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Dar permisos de ejecución
        run: chmod +x gradlew
        
      - name: Construir APK Debug
        run: ./gradlew assembleDebug
        
      - name: Guardar el APK
        uses: actions/upload-artifact@v4
        with:
          name: FireGuard-Android15
          path: app/build/outputs/apk/debug/app-debug.apk
